const app = Vue.createApp({
    data(){
        return {
            IDK: "pinkBG",
            APP_TITLE:'THE PERFECT APP'
        }
    }
})
app.mount('#app')

Vue.createApp({
    data() {
        return {
        NOTHING: "_blank"
    }
}
}).mount('#specialUrl')
	
Vue.createApp({
    data(){
        return{
            IMG:"https://i.pinimg.com/736x/21/f2/21/21f22151d5839ff7e212714623e693ce.jpg",
            showed:true,
            showed_message: "Hide"
        }
    },
    methods:{
        toogle_button_pic(){
            this.showed=!this.showed
            this.showed_message= this.showed? "Hide":"Show"
        }
    }
    }
).mount("#img_vue")


Vue.createApp({
    template:"<b>This is a template generated by inyection</b>"

}
).mount("#template_generated")

Vue.createApp({
    data(){
        return{
            show_paragraph:true,
            show_hide:"Hide",
            num_clicks:1,
            bool_value: true
        }
    },
    methods:{
        increase_num_clicks(){
            this.num_clicks++
        },
        decrease_num_clicks(){
            this.num_clicks--
        },
        define_num_clicks(num){
            this.num_clicks=num
        },

        toogle_show_hide_paragraph(){
            this.show_paragraph=!this.show_paragraph
            this.show_hide= this.show_paragraph? "Hide":"Show"
        }


    }
}


).mount("#counter_clicks")